language: java
script: ./gradlew build jacocoTestReport
before_install:
  - chmod +x gradlew
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
env:
  matrix:
  - TERM=dumb
after_success:
  - ./gradlew jacocoRootReport coveralls
